// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

// export const environment = {
//   production: true,
//   version: env.npm_package_version + '-dev',
//   masterServerUrl: 'http://gatewaydevapi.corp.osoftec.com/api/master',
//   commonServerUrl: 'http://gatewaydevapi.corp.osoftec.com/api/common',
//   serverUrl: 'http://gatewaydevapi.corp.osoftec.com/api/security',
//   coreBaseApiUrl: 'http://gatewaydevapi.corp.osoftec.com/api/base',
//   envName: 'PROD',
//   RazorKey: 'rzp_live_NsPdlgJCH7sDYM'

  
// }
export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  masterServerUrl: 'http://gatewaydevapi.corp.osoftec.com/api/master',
  commonServerUrl: 'http://gatewaydevapi.corp.osoftec.com/api/common',
  serverUrl: 'http://gatewaydevapi.corp.osoftec.com/api/security',
  coreBaseApiUrl: 'http://gatewaydevapi.corp.osoftec.com/api/base',
  envName: 'DEV',
  RazorKey: 'rzp_live_NsPdlgJCH7sDYM'

  
}


/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
